name: Minify CSS and Deploy

on:
  push:
    branches:
      - main # Change this to your default branch if different

jobs:
  minify-css:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Use the latest LTS version or your required version

      # Install necessary dependencies
      - name: Install npm packages
        run: |
          npm install clean-css-cli --save-dev

      # Minify CSS files
      - name: Minify CSS
        run: |
          npx clean-css -o css/Totter-Flow.min.css css/Totter-Flow.css
          npx clean-css -o css/Totter-Flow-Utilities.min.css css/Totter-Flow-Utilities.css

      # Commit changes if any
      - name: Commit changes
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Action"
          git add css/*.min.css
          git commit -m "Update minified CSS files" || echo "No changes to commit"

      # Push changes back to the repository
      - name: Push changes
        run: git push
